
import { Product } from '@/types/product';
import { PlaceHolderImages } from './placeholder-images';

const getPlaceholderImg = (id: string) => {
  return PlaceHolderImages.find(img => img.id === id)?.imageUrl || 'https://placehold.co/600x800/000000/000000/png';
};

export const PRODUCTS: Product[] = [
  {
    id: 'f1',
    name: 'Purple Urkle',
    description: 'A California classic with deep purple hues and a sweet, grape-like aroma. These buds are heavy with trichomes and provide a deeply relaxing experience.',
    category: 'Flower',
    price: 60,
    imageUrl: getPlaceholderImg('macro-flower-1'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Indica'],
    isNewArrival: true
  },
  {
    id: 'f2',
    name: 'Granddaddy Purple',
    description: 'Famous for its oversized bud structure and incredibly vibrant orange pistils. This indica-dominant strain is a macro photographer\'s dream.',
    category: 'Flower',
    price: 55,
    imageUrl: getPlaceholderImg('macro-flower-2'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Indica'],
    isNewArrival: true
  },
  {
    id: 'f3',
    name: 'Ghost Train Haze',
    description: 'A potent sativa-dominant strain known for its heavy resin production and cerebral uplift. The buds are dense and frosted with crystalline trichomes.',
    category: 'Flower',
    price: 65,
    imageUrl: getPlaceholderImg('macro-flower-3'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Sativa'],
    isNewArrival: true
  },
  {
    id: 'f4',
    name: 'Wedding Cake',
    description: 'An indica-leaning hybrid with a rich, tangy flavor profile. The buds are dark green and purple, completely coated in sugary resin.',
    category: 'Flower',
    price: 50,
    imageUrl: getPlaceholderImg('macro-flower-4'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Hybrid'],
  },
  {
    id: 'f5',
    name: 'Northern Lights',
    description: 'A pure indica known for its resinous buds and fast flowering. It has a sweet and spicy aroma that radiates through its crystalline coating.',
    category: 'Flower',
    price: 45,
    imageUrl: getPlaceholderImg('macro-flower-1'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Indica'],
  },
  {
    id: 'f6',
    name: 'Sour Diesel',
    description: 'A world-class sativa with a pungent, fuel-like aroma. The buds are light green with fiery orange hairs that pop against dark backdrops.',
    category: 'Flower',
    price: 55,
    imageUrl: getPlaceholderImg('macro-flower-2'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Sativa'],
  },
  {
    id: 'f7',
    name: 'Girl Scout Cookies',
    description: 'An OG Kush and Durban Poison hybrid cross whose reputation grew too large to stay within the borders of its California homeland.',
    category: 'Flower',
    price: 60,
    imageUrl: getPlaceholderImg('macro-flower-3'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Hybrid'],
  },
  {
    id: 'f8',
    name: 'OG Kush',
    description: 'The backbone of many modern West Coast strains. It has a unique terpene profile that boasts a complex aroma with notes of fuel, skunk, and spice.',
    category: 'Flower',
    price: 65,
    imageUrl: getPlaceholderImg('macro-flower-4'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Hybrid'],
  },
  {
    id: 'f9',
    name: 'White Widow',
    description: 'Among the most famous strains worldwide. A balanced hybrid first bred in the Netherlands, known for its extreme "white" trichome coverage.',
    category: 'Flower',
    price: 50,
    imageUrl: getPlaceholderImg('macro-flower-1'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Hybrid'],
  },
  {
    id: 'f10',
    name: 'Jack Herer',
    description: 'A sativa-dominant strain that has gained as much renown as its namesake, the marijuana activist and author of The Emperor Wears No Clothes.',
    category: 'Flower',
    price: 55,
    imageUrl: getPlaceholderImg('macro-flower-2'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Sativa'],
  },
  {
    id: 'f11',
    name: 'Blue Dream',
    description: 'A sativa-dominant hybrid originating in California, Blue Dream has achieved legendary status among West Coast strains.',
    category: 'Flower',
    price: 58,
    imageUrl: getPlaceholderImg('macro-flower-3'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Hybrid'],
  },
  {
    id: 'f12',
    name: 'Skywalker OG',
    description: 'Skywalker OG is a potent indica-dominant hybrid strain that may just take you to a galaxy far, far away.',
    category: 'Flower',
    price: 62,
    imageUrl: getPlaceholderImg('macro-flower-4'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Indica'],
  },
  {
    id: 'f13',
    name: 'Chemdawg',
    description: 'Chemdawg has developed quite the name for itself over the years. Between its mysterious origin and ambiguous genetics.',
    category: 'Flower',
    price: 64,
    imageUrl: getPlaceholderImg('macro-flower-1'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Hybrid'],
  },
  {
    id: 'f14',
    name: 'Amnesia Haze',
    description: 'With earthy flavors of lemons and citrus, Amnesia Haze is a perfect sativa strain to start your day with a smile.',
    category: 'Flower',
    price: 60,
    imageUrl: getPlaceholderImg('macro-flower-2'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Sativa'],
  },
  {
    id: 'f15',
    name: 'Bubba Kush',
    description: 'Bubba Kush is an indica strain that has gained notoriety in the US and beyond for its heavy tranquilizing effects.',
    category: 'Flower',
    price: 55,
    imageUrl: getPlaceholderImg('macro-flower-3'),
    sizes: ['3.5g', '7g', '14g', '28g'],
    colors: ['Indica'],
  },
  {
    id: 'c1',
    name: 'Live Resin Diamonds',
    description: 'Concentrated THC-A crystals in a terpene-rich sauce. Perfect for connoisseurs seeking peak potency and flavor.',
    category: 'Concentrates',
    price: 75,
    imageUrl: getPlaceholderImg('macro-concentrate'),
    sizes: ['1g', '2g'],
    colors: ['Extract'],
  },
  {
    id: 'e1',
    name: 'Midnight Berry Gummies',
    description: 'Artisanal vegan gummies infused with full-spectrum cannabis oil for a balanced, long-lasting effect.',
    category: 'Edibles',
    price: 25,
    imageUrl: getPlaceholderImg('macro-edible'),
    sizes: ['10-Pack', '20-Pack'],
    colors: ['Mixed Berry'],
  }
];
